.version: &version "16.4.17-dev.proxyipv6.5"

apiVersion: v2
name: teleport-plugin-discord
description: A Helm chart for the Teleport Discord Plugin
type: application
version: *version
appVersion: *version
