.version: &version "17.5.2-dev.ctmu.1"

apiVersion: v2
name: teleport-plugin-event-handler
description: A Helm chart for Teleport Event Handler Plugin
type: application
version: *version
appVersion: *version
