.version: &version "19.0.0-dev.electron.37.1.0"

apiVersion: v2
name: teleport-plugin-event-handler
description: A Helm chart for Teleport Event Handler Plugin
type: application
version: *version
appVersion: *version
