.version: &version "17.3.3-dev-sailpoint.scim"

apiVersion: v2
name: teleport-plugin-event-handler
description: A Helm chart for Teleport Event Handler Plugin
type: application
version: *version
appVersion: *version
