.version: &version "17.4.4-dev.steve.dbmultimfa.1"

name: teleport-operator
apiVersion: v2
version: *version
appVersion: *version
description: Teleport Operator provides management of select Teleport resources.
icon: https://goteleport.com/static/teleport-symbol-bimi.svg
keywords:
  - Teleport
