.version: &version "17.3.1-dev.vnet-windows.1"

apiVersion: v2
name: teleport-plugin-jira
description: A Helm chart for the Teleport Jira Plugin
type: application
version: *version
appVersion: *version
