.version: &version "18.0.0-dev.gus-uni-rust-override.3"

apiVersion: v2
name: teleport-plugin-jira
description: A Helm chart for the Teleport Jira Plugin
type: application
version: *version
appVersion: *version
