.version: &version "19.0.0-dev.electron.37.1.0"

apiVersion: v2
name: teleport-plugin-jira
description: A Helm chart for the Teleport Jira Plugin
type: application
version: *version
appVersion: *version
