.version: &version "18.0.0-dev.fred-env-var-migration-1-25"

apiVersion: v2
name: teleport-plugin-jira
description: A Helm chart for the Teleport Jira Plugin
type: application
version: *version
appVersion: *version
