.version: &version "17.4.8-dev.scim"

apiVersion: v2
name: teleport-plugin-datadog
description: A Helm chart for the Teleport Datadog Incident Management Plugin
type: application
version: *version
appVersion: *version

dependencies:
  - name: tbot
    version: *version
    condition: tbot.enabled
