.version: &version "16.5.0-dev.hugoau.1"

apiVersion: v2
name: teleport-plugin-datadog
description: A Helm chart for the Teleport Datadog Incident Management Plugin
type: application
version: *version
appVersion: *version

dependencies:
  - name: tbot
    version: *version
    condition: tbot.enabled
