.version: &version "17.4.9-dev.saml-postform-request.1"

apiVersion: v2
name: teleport-plugin-datadog
description: A Helm chart for the Teleport Datadog Incident Management Plugin
type: application
version: *version
appVersion: *version

dependencies:
  - name: tbot
    version: *version
    condition: tbot.enabled
