apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  labels:
    teleport.dev/discover: "true"  # Teleport Discovery Label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-app
  labels:
    teleport.dev/discover: "true"  # Teleport Discovery Label
spec:
  selector:
    app: nginx-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
