.version: &version "17.5.5-dev.sclevine.2"

apiVersion: v2
name: teleport-plugin-msteams
description: A Helm chart for the Teleport MsTeams Plugin
type: application
version: *version
appVersion: *version
