.version: &version "17.4.4-dev.steve.dbmultimfa.1"

apiVersion: v2
name: teleport-plugin-msteams
description: A Helm chart for the Teleport MsTeams Plugin
type: application
version: *version
appVersion: *version
