.version: &version "16.4.19-dev.ravicious.2"

apiVersion: v2
name: teleport-plugin-mattermost
description: A Helm chart for the Teleport Mattermost Plugin
type: application
version: *version
appVersion: *version
