.version: &version "17.4.6-dev.multidomain.1"

apiVersion: v2
name: teleport-plugin-mattermost
description: A Helm chart for the Teleport Mattermost Plugin
type: application
version: *version
appVersion: *version
