.version: &version "16.0.0-dev.camh.dbp.2.1"

apiVersion: v2
name: teleport-plugin-mattermost
description: A Helm chart for the Teleport Mattermost Plugin
type: application
version: *version
appVersion: *version
