.version: &version "18.0.3-dev.hugocanary.3"

apiVersion: v2
name: teleport-plugin-mattermost
description: A Helm chart for the Teleport Mattermost Plugin
type: application
version: *version
appVersion: *version
