.version: &version "18.0.0-dev.joerger.2"

name: teleport-relay
apiVersion: v2
version: *version
appVersion: *version
description: This chart deploys the Teleport Relay service.
icon: https://goteleport.com/static/teleport-symbol-bimi.svg
keywords:
  - Teleport
