.version: &version "17.3.4-dev.debug.alpn.upgrade.1"

apiVersion: v2
name: teleport-plugin-email
description: A Helm chart for the Teleport Email Plugin
type: application
version: *version
appVersion: *version
