.version: &version "18.0.0-dev.ravicious.26"

apiVersion: v2
name: teleport-plugin-email
description: A Helm chart for the Teleport Email Plugin
type: application
version: *version
appVersion: *version
